export const SELECT_TRIP_FOR_BOOKING = 'SELECT_TRIP_FOR_BOOKING'
export const CANCEL_TRIP_FOR_BOOKING = 'CANCEL_TRIP_FOR_BOOKING'

export const SAVE_BOOKING_INFO = 'SAVE_BOOKING_INFO'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const CONFIRM_BOOKING_REQUEST = 'CONFIRM_BOOKING_REQUEST'
export const CONFIRM_BOOKING_SUCCESS = 'CONFIRM_BOOKING_SUCCESS'
export const CONFIRM_BOOKING_FAIL = 'CONFIRM_BOOKING_FAIL'

export const GET_BOOKED_TRIP_REQUEST = 'GET_BOOKED_TRIP_REQUEST'
export const GET_BOOKED_TRIP_SUCCESS = 'GET_BOOKED_TRIP_SUCCESS'
export const GET_BOOKED_TRIP_FAIL = 'GET_BOOKED_TRIP_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST'
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS'
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL'