export const RATE_DESTINATION_REQUEST = 'RATE_DESTINATION_REQUEST'
export const RATE_DESTINATION_SUCCESS = 'RATE_DESTINATION_SUCCESS'
export const RATE_DESTINATION_FAIL = 'RATE_DESTINATION_FAIL'
export const RATE_DESTINATION_RESET = 'RATE_DESTINATION_RESET'