export const TRIP_LIST_REQUEST = 'TRIP_LIST_REQUEST'
export const TRIP_LIST_SUCCESS = 'TRIP_LIST_SUCCESS'
export const TRIP_LIST_FAIL = 'TRIP_LIST_FAIL'

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST'
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS'
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL'


export const TRIP_CREATE_REVIEW_REQUEST = 'TRIP_CREATE_REVIEW_REQUEST'
export const TRIP_CREATE_REVIEW_SUCCESS = 'TRIP_CREATE_REVIEW_SUCCESS'
export const TRIP_CREATE_REVIEW_FAIL = 'TRIP_CREATE_REVIEW_FAIL'
export const TRIP_CREATE_REVIEW_RESET = 'TRIP_CREATE_REVIEW_RESET'

